server:
  port: 9527

spring:
  application:
    name: springcloud-zuul #微服务名称

# eureka 注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: #实例的id
    instance-id: zuul9527.com
    prefer-ip-address: true # 显示ip


# zull 路由网关配置
zuul:
  prefix: /bdqn   #设置公共的前缀
  ignored-services: "*"   # 不能再使用这个路径访问了，*： 忽略,隐藏全部的服务名称~
  routes:
    provider:   #服务名称
      path: /microservicecloud-dept/**  #映射路径
      serviceId: provider   # eureka注册中心的服务提供方路由名称
    providertwo:   #设置第二个服务名称
      path: /microservicecloud-dept2/**  #映射路径
      serviceId: providertwo


